import ts from '../src/treibstoff.js';

QUnit.module('Test treibstoff', hooks => {

    QUnit.test('Test api members', assert => {
        let members = [];
        for (let prop in ts) {
            members.push(prop);
        }
        assert.deepEqual(members, [
            'Ajax',
            'AjaxAction',
            'AjaxDestroy',
            'AjaxDispatcher',
            'AjaxEvent',
            'AjaxForm',
            'AjaxHandle',
            'AjaxOperation',
            'AjaxOverlay',
            'AjaxParser',
            'AjaxPath',
            'AjaxRequest',
            'AjaxSpinner',
            'AjaxUtil',
            'ajax',
            'Events',
            'Form',
            'FormCheckbox',
            'FormField',
            'FormInput',
            'FormRemoteSelect',
            'FormSelect',
            'KeyState',
            'ChangeListener',
            'ClickListener',
            'changeListener',
            'clickListener',
            'Motion',
            'Dialog',
            'Message',
            'Overlay',
            'get_overlay',
            'show_dialog',
            'show_error',
            'show_info',
            'show_message',
            'show_warning',
            'HTMLParser',
            'Parser',
            'SVGParser',
            'TemplateParser',
            'compile_svg',
            'compile_template',
            'extract_number',
            'AttrProperty',
            'BoundProperty',
            'ButtonProperty',
            'CSSProperty',
            'DataProperty',
            'InputProperty',
            'Property',
            'SVGProperty',
            'TextProperty',
            'create_cookie',
            'create_svg_elem',
            'deprecate',
            'get_elem',
            'json_merge',
            'load_svg',
            'parse_path',
            'parse_query',
            'parse_svg',
            'parse_url',
            'query_elem',
            'read_cookie',
            'set_default',
            'set_svg_attrs',
            'set_visible',
            'svg_ns',
            'uuid4',
            'Button',
            'Collapsible',
            'HTMLWidget',
            'SVGContext',
            'Visibility',
            'Widget',
            'WS_STATE_CLOSED',
            'WS_STATE_CLOSING',
            'WS_STATE_CONNECTING',
            'WS_STATE_OPEN',
            'Websocket'
        ]);
    });

});
