name: Test treibstoff

on:
  push:

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          npm --save-dev install \
            qunit \
            karma \
            karma-qunit \
            karma-coverage \
            karma-chrome-launcher \
            karma-module-resolver-preprocessor
          npm --no-save install https://github.com/jquery/jquery#main

      - name: Run tests
        run: |
          node_modules/karma/bin/karma start karma.conf.js
