name: Tests

on: [push]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: |
          make install

      - name: Run tests
        run: |
          make wtr
