name: Test treibstoff

on:
  push:

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          make install

      - name: Run tests
        run: |
          make test
